#!/bin/bash

# docker install
# https://www.docker.com/
curl -fsSL https://get.docker.com/ | sudo sh
sudo usermod -aG docker $USER


# docker-compose install
sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

